version: "3.9"
services:
  app:
    image: wardsmetscode/python-api-test
    ports:
      - "80:80"
#  db:
#    image: postgres
#    restart: always
#    environment:
#      POSTGRES_PASSWORD: example
#
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - "8080:8080"

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: stt_db
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - "8081:8081"
